baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'main'

DefaultContentLanguage = "en"
[languages]
  [languages.en]
    disabled = false
    languageCode = 'en-US'
    languageDirection = 'ltr'
    languageName = 'English'
    title = 'Personal Site'
    weight = 2
    [languages.en.params]
      subtitle = 'test'
  [languages.ko]
    disabled = false
    languageCode = 'ko-KR'
    languageDirection = 'ltr'
    languageName = '한국어'
    title = '개인 사이트'
    weight = 1
    [languages.de.params]
      subtitle = '테스트'